#
# This is a Shiny web application. You can run the application by clicking
# the 'Run App' button above.
#
# Find out more about building applications with Shiny here:
#
#    http://shiny.rstudio.com/
#

# Load model
load("some0rr.fit_PSSTTWEA.rda")
load("some0rr.bestlam_PSSTTWEA.R")

# This model uses the daily precipitation (.1mm), snowdepth (in), snowfall(in), MaxTemp(F), MinTemp(F), MaxWindSpeed(m/s), Elevation (Ft), and Aspect


#library(dplyr)
library(glmnet)
library(shiny)

# Define UI for application 
ui <- shinyUI(fluidPage(#
  # Application title
  titlePanel("Avalanche Predictor"),
  sidebarLayout(#
    sidebarPanel(strong("Important")," This models predictions are based on observations of avalanches from people like you.  This is a tool, just like an ECT.  Be conservative in your judgement.  Play with the model, you will notice that an increase in wind leads to a decrease in predicted avalanche activity.  This goes against what we know about avalanches, this is likely an artifact due to the fact that people do not go into the field when wind is high and make observations.", br(), br(), "In short:", strong("Use at your own risk... skull and crossbones!"),
                 br(), br(),#
                 numericInput("preci", "Daily Precipitation (in)", 0,  min = 0, max = 10, step = 0.1),
                 numericInput("snwd","Snow depth (in)", 35, min = 0, max = 300, step = 1),
                 numericInput("snf","Daily Snowfall (in)", 1.4, min = 0, max = 150, step = 1),
                 numericInput("mxt","Maximum Temperature (degrees Farenheit)", 47, min = -40, max = 100, step = 0.1),
                 numericInput("mint","Minimum Temperature (degrees Farenheit)", 29, min = -40, max = 100, step = 0.1),
                 numericInput("mxws","Max Wind Speed (miles per hour)", 27, min = 0, max = 200, step = 0.1),
                 numericInput("elev", "Elevation (ft)", 9600, min=5200, max = 11500, step = 50),
                 radioButtons("aspect","Aspect",choices = c("North", "Northwest", "West", "Southwest", "South", "Southeast", "East", "Northeast"),selected = "Northeast"), width = 8),
    mainPanel(br(),br(),br(), br(),br(),br(),br(),br(),br(),br(),br(), br(),br(),"Based on reported historical observations and the inputs you supplied.", br(), strong("It is "), h1(textOutput("results1")), strong(" that you would encounter an avalance"), br(), br(), "For the curious, the raw output based on your inputs is", textOutput("results2"),br(), "With 0 being the lowest value and 1 being the largest value attained.  Note: these are not probabilities.", width = 4)),
  "This model was created to provide another tool in evaluating danger in the backcountry.  The model was generated by datasets provided by the Utah Avalanche Center, and the NOAA.  The model was populated using ridge regression, and has an accuracy normally distributed with a mean of 74% and a standard deviation of 3%.  Further the model has a sensitivity of 0.5 and a specificity of about 0.8.  I was only able to use about 450 observations in constructing the model, so it is far from perfect.  If you would like to contribute please visit the project page at ", 
  a("https://github.com/justinlboyer/avalanche", href = "https://github.com/justinlboyer/avalanche",target="_blank"), br(), "If you post observations, please try to always include elevation, and location.", br(), br()
  )#
)
   
#Conversions
#(f-32)*5/9
#.45meps = 1 mph
#1in = 25.4mm
   
   # Define Server
   server <- function(input, output, session){
     value <- reactive(#
       {choices = c("North", "Northwest", "West", "Southwest", "South", "Southeast", "East", "Northeast")
     aspt <- numeric(0)
     for (i in choices) {
       aspt[i] <- ifelse(input$aspect==i, 1, 0)
     }
     x.in <- t(c(input$preci*25.4, input$snwd*25.4, input$snf*25.4, (input$mxt-32)*5/9, (input$mint-32)*5/9, input$mxws*0.45, input$elev, aspt[1],aspt[2],aspt[3],aspt[4],aspt[5],aspt[6],aspt[7],aspt[8]))
     rr.pred <- predict(rr.fit2, s=rr.bestlam, newx = x.in)
     rr.pred[rr.pred <0] <- 0
     rr.pred})
     output$results1 <- renderText({
       zeroone <- round(tanh(value()))
       ifelse(zeroone==0,"Unlikely","Likely")
       
   })
     output$results2 <- renderText({value()})
   }
   
shinyApp(ui = ui, server = server)  
