#
# This is a Shiny web application. You can run the application by clicking
# the 'Run App' button above.
#
# Find out more about building applications with Shiny here:
#
#    http://shiny.rstudio.com/
#

# Load model
load("mostZrr.fit_PSSTTWA.rda")
load("mostZrr.bestlam.R")

# This model uses the daily precipitation (.1mm), snowdepth (in), snowfall(in), MaxTemp(F), MinTemp(F), MaxWindSpeed(m/s)

#Conversions
#(f-32)*5/9
#.45meps = 1 mph

#library(dplyr)
library(glmnet)
library(shiny)

# Define UI for application 
ui <- shinyUI(fluidPage(#
  # Application title
  titlePanel("Avalanche Predictor"),
  sidebarLayout(#
    sidebarPanel(strong("Important")," This models predictions are based on observations of avalanches from people like you.  This is a tool, just like an ECT.  Be conservative in your judgement.  Play with the model, you will notice that an increase in wind leads to a decrease in predicted avalanche activity.  This goes against what we know about avalanches, this is likely an artifact due to the fact that people do not go into the field when wind is high and make observations.", br(), br(), "In short:", strong("Use at your own risk... skull and crossbones!"),
                 br(), br(),#
                 numericInput("preci", "Daily Precipitation (in)", 0,  min = 0, max = 10, step = 0.1),
                 numericInput("snwd","Snow depth (in)", 35, min = 0, max = 300, step = 1),
                 numericInput("snf","Daily Snowfall (in)", 1.4, min = 0, max = 150, step = 1),
                 numericInput("mxt","Maximum Temperature (degrees Farenheit)", 47, min = -40, max = 100, step = 0.1),
                 numericInput("mint","Minimum Temperature (degrees Farenheit)", 29, min = -40, max = 100, step = 0.1),
                 numericInput("mxws","Max Wind Speed (miles per hour)", 27, min = 0, max = 200, step = 0.1),
                 radioButtons("aspect","Aspect",choices = c("North", "Northwest", "West", "Southwest", "South", "Southeast", "East", "Northeast"),selected = "Northeast"), width = 8),
    mainPanel(br(),br(),br(), br(),br(),br(),br(),br(),br(),br(),br(), br(),br(),"Based on reported historical observations and the inputs you supplied.", strong("The number of predicted avalanches you could encounter is"), h1(textOutput("results")), width = 4)),
  "This model was created to provide another tool in evaluating danger in the backcountry.  The model was generated by datasets provided by the Utah Avalanche Center, and the NOAA.  The model was populated using ridge regression, and has an approximate accuracy normally distributed about 54% with a standard deviation of 2%.  If you would like to contribute please visit the project page at ", 
  a("https://github.com/justinlboyer/avalanche", href = "https://github.com/justinlboyer/avalanche",target="_blank"), br(), "If you post observations, please try to always include elevation, and location so that I can include these in a future version.", br(), br()
  )#
)
   

   
   # Define Server
   server <- function(input, output, session){
     output$results <- renderText({
       choices = c("North", "Northwest", "West", "Southwest", "South", "Southeast", "East", "Northeast")
       aspt <- numeric(0)
       for (i in choices) {
         aspt[i] <- ifelse(input$aspect==i, 1, 0)
       }
       x.in <- t(c(input$preci, input$snwd, input$snf, input$mxt, input$mint, input$mxws*0.45, aspt[1],aspt[2],aspt[3],aspt[4],aspt[5],aspt[6],aspt[7],aspt[8]))
       rr.pred <- predict(rr.fit2, s=rr.bestlam, newx = x.in)
       #rr.pred
       val <- ifelse(rr.pred >= 0, trunc(rr.pred), 0)
       val
   })
   }
   
shinyApp(ui = ui, server = server)   
